apiVersion: v1
kind: ConfigMap
metadata:
  name: transactions-env-config
  namespace: zamazon
data:
  HTTP_PORT: ":8080"
  DSN: "host=postgres-transactions-service user=root password=root dbname=zamazon-db-transactions port=5432 sslmode=disable"
  JWT_SECRET : "qhx5shDMjBChXdPrxzFmCr+W09Dz4uPvUGUp66xCrCs="
  APP_SECRET: "zamazon-secret"
  STRIPE_API_KEY: "sk_test_51QxPP7RseTn0ad94FL0owOMoWrdfutpZ16EDhG8VjDGu9jHC0g7wtu7SpbWiYjrPnQ2URwPPBZju4WAiNJt1QDRR006pbNACnM"
  STRIPE_PUB_KEY: "pk_test_51QxPP7RseTn0ad94AwALlRx3z9bZ61lkcoHiJuU13T8pyNskJAGZ3FMCGlYxAfAF3s73hC8H54QAc9NPSYSyaiz400IU6O1k7q"
  SUCCESS_URL: "http://localhost:4200"
  CANCEL_URL: "http://localhost:4200"
  USER_SERVICE_URL: "http://users-service:80"
  AUTH_SERVICE_URL: "http://auth-service:80"
