apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-deployment
  namespace: zamazon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions
  template:
    metadata:
      labels:
        app: transactions
    spec:
      containers:
        - name: transactions
          image: sharat789/zamazon-be-ms-transactions:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: transactions-env-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"